### ISSUE TITLE
Druid cancelaura form

### ISSUE THREAD

**Issue by Paddyay** [exochron/MountJournalEnhanced#117]
Im using the Cataclysm version of this addon and when im using the favourite mount macro/button when i am in Cat form or bear form or any other form for that matter it just says "You are in shapeshift form" and doesnt mount me up. This is not how it normally works when binding a mount to a button, then it takes me out of form as usual.

Is there a way to fix this either via adding "/cancelaura cat form" etc in the macro or just add something in the addon itself

I could add it myself to the macro but i have to do that every time the macro resets or changes

**Comment by exochron** [comment]
Thank you for reporting this. Your right, in retail you get automatically out of the druid form with the random mount button. So it seems there are still some kinks to random mount system in the Cata client. That might be one of the reasons why Blizzard hasn't officially published it. <^.^>
Lucky MJE uses a simple macro and there is the /cancelform command for that.
So it should be fixed with version 2.37 :)

**Comment by ScottEWMiller** [comment]
Is there any way to exclude shadowform from this change? Currently, I have to reactivate shadow form every time I mount which is a bit annoying.
